/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logical;

/**
 *
 * @author julil
 */

import java.text.DecimalFormat;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonAltura = new javax.swing.JButton();
        buttonArea = new javax.swing.JButton();
        buttonPerimetro = new javax.swing.JButton();
        textAltura = new javax.swing.JTextField();
        textArea = new javax.swing.JTextField();
        textPerimetro = new javax.swing.JTextField();
        textLado = new javax.swing.JTextField();
        buttonBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Valor del lado ");

        buttonAltura.setText("Altura");
        buttonAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlturaActionPerformed(evt);
            }
        });

        buttonArea.setText("Area");
        buttonArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAreaActionPerformed(evt);
            }
        });

        buttonPerimetro.setText("Perimetro");
        buttonPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerimetroActionPerformed(evt);
            }
        });

        buttonBorrar.setText("Borrar");
        buttonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 247, Short.MAX_VALUE)
                        .addComponent(textLado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(buttonArea)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(buttonPerimetro)
                                        .addGap(18, 18, 18)
                                        .addComponent(textPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(buttonAltura))))))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonBorrar)
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPerimetro))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAltura)
                    .addComponent(textAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonArea))
                .addGap(18, 18, 18)
                .addComponent(buttonBorrar)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerimetroActionPerformed
        //Leemos valores por la bandeja de texto
        int edge = Integer.parseInt(textLado.getText());
        //Creamos el objeto
        TrianguloEquilatero triangulo = new TrianguloEquilatero(edge);
        //Mostramos el elemento por la bandeja respectiva de texto
        textPerimetro.setText(String.valueOf(triangulo.perimetroTrian()));
    }//GEN-LAST:event_buttonPerimetroActionPerformed

    private void buttonAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAreaActionPerformed
        //Creacion de clase para mostrar dos cifras decimas
        DecimalFormat df = new DecimalFormat("#.##");
        //Leemos valores por la bandeja de texto
        int edge = Integer.parseInt(textLado.getText());
        //Creamos el objeto
        TrianguloEquilatero triangulo = new TrianguloEquilatero(edge);
        //Mostramos el elemento por la bandeja respectiva de texto
        textArea.setText(df.format(triangulo.areaTrian()));
    }//GEN-LAST:event_buttonAreaActionPerformed

    private void buttonAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlturaActionPerformed
        //Creacion de clase para mostrar dos cifras decimas
        DecimalFormat df = new DecimalFormat("#.##");        
        //Leemos valores por la bandeja de texto
        int edge = Integer.parseInt(textLado.getText());
        //Creamos el objeto
        TrianguloEquilatero triangulo = new TrianguloEquilatero(edge);
        //Mostramos el elemento por la bandeja respectiva de texto
        textAltura.setText(df.format(triangulo.alturaTrian()));
    }//GEN-LAST:event_buttonAlturaActionPerformed

    private void buttonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarActionPerformed
        textAltura.setText("");
        textArea.setText("");
        textPerimetro.setText("");
    }//GEN-LAST:event_buttonBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAltura;
    private javax.swing.JButton buttonArea;
    private javax.swing.JButton buttonBorrar;
    private javax.swing.JButton buttonPerimetro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textAltura;
    private javax.swing.JTextField textArea;
    private javax.swing.JTextField textLado;
    private javax.swing.JTextField textPerimetro;
    // End of variables declaration//GEN-END:variables
}
